[profile.default]
via_ir = true
optimizer = true
optimizer_runs = 200
src = "src"
out = "out"
libs = ["lib"]
ffi = true
ast = true
build_info = true
extra_output = ["storageLayout"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
[rpc_endpoints]
sepolia = "https://open-campus-codex-sepolia.drpc.org"
educhain = "https://rpc.edu-chain.raas.gelato.cloud"
educhain-testnet = "https://open-campus-codex-sepolia.drpc.org"
